---

system:
  packages:
    - deltarpm
    - dpkg
    - unzip

install_jdk: true
java_version: 7u261

mount_point: "/u01"
device_name: "/dev/xvdb"
mount_owner: "{{ system_users.0.name }}"
mount_group: "{{ system_users.0.group }}"

mw_home: "{{ mount_point }}/app/oracle/middleware"
wls_home: "{{ mw_home }}/wlserver_10.3"
java_home: "{{ lookup('env', 'JAVA_HOME') or '/usr/java/latest' }}"

system_users:
  - name: oracle
    uid: 1200
    group: oinstall
    gid: 1100
    profile: |
          alias ll='ls -lah'
          alias cp='cp -iv'
          export MW_HOME={{ mw_home }}
          export WLS_HOME={{ wls_home }}
          export JAVA_HOME={{ java_home }}
          PATH=$JAVA_HOME/bin:$PATH
          export PATH

artefact_path: "delius-core/oracle/wls"
weblogic_artefacts:
  - name: 'wls1036_generic.jar'
  - name: 'p27238412_1036_Generic.zip'
  - name: 'p30857748_1036_Generic.zip'
  - name: 'p11817754_10360200114_Generic.zip'

weblogic_patches:
  # Patch 27238412: SMART UPDATE TOOL ENHANCEMENT V3
  - name: "p27238412_1036_Generic"
    command: ". ~/.bash_profile && . ${WLS_HOME}/server/bin/setWLSEnv.sh > /dev/null 2>&1 && cd ${MW_HOME}/utils/bsu/cache_dir && bash bsu_update.sh install"
    creates_file: "bsu_update.sh"
  # Patch 30857748: WLS PATCH SET UPDATE 10.3.6.0.200414
  - name: "p30857748_1036_Generic"
    creates_file: "Q3ZB.jar"
    command: ". ~/.bash_profile && . ${WLS_HOME}/server/bin/setWLSEnv.sh > /dev/null 2>&1 && cd ${MW_HOME}/utils/bsu && ./bsu.sh -install -patch_download_dir=${MW_HOME}/utils/bsu/cache_dir -patchlist=Q3ZB -prod_dir=${WLS_HOME} -verbose -log=Q3ZB_patch.log"
  # Overlay: FEATURE TO COPY THE WEBLOGIC AUTHENTICATED USER IN THE ORACLE CLIENT ID FIELD
  - name: "p11817754_10360200114_Generic"
    creates_file: "PZ7S.jar"
    command: ". ~/.bash_profile && . ${WLS_HOME}/server/bin/setWLSEnv.sh > /dev/null 2>&1 && cd ${MW_HOME}/utils/bsu && ./bsu.sh -install -patch_download_dir=${MW_HOME}/utils/bsu/cache_dir -patchlist=PZ7S -prod_dir=${WLS_HOME} -verbose -log=PZ7S_patch.log"

nodemgr_port: "5556"
